name: petcare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.16.0
  firebase_auth: ^4.9.4
  cloud_firestore: ^4.12.0
  go_router: ^8.1.0
  firebase_analytics: ^10.0.0
  firebase_storage: ^11.6.5
  percent_indicator: ^4.2.4
  syncfusion_flutter_charts: ^28.1.41
  image_picker: ^1.1.2
  intl: ^0.18.0
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dog1.png
    - assets/dog2.png
    - assets/dog3.png
    - assets/google_icon.png
    - assets/facebook_icon.png
    - assets/apple_icon.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
